
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        ADD_NEW_PRODUK : "ADD PRODUK",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        PRODUK_DELETE : "PRODUK_DELETE",
        PENGELUARAN_DELETE : "PENGELUARAN_DELETE",
        PEMBELIAN_DELETE : "PEMBELIAN_DELETE",
        PENITIP_DELETE : "PENITIP_DELETE",
        BAHAN_BAKU_DELETE : "BAHAN_BAKU_DELETE",
        HAMPERS_DELETE : "HAMPERS_DELETE",
    },
});
